#!/bin/bash

set -e

# Generate config
function generateconfig() {
  # Config nginx for Zeppelin
  echo "generating zeppelin-auth-setting..."
  local SITE_AVL_CONF=/etc/nginx/sites-available/zeppelin-auth-setting
  local SITE_ENABLE_CONF=/etc/nginx/sites-enabled/zeppelin-auth-setting
  /generate_config.py --template "/templates/zeppelin-auth-setting.template" --conf "${SITE_AVL_CONF}"
  test -L ${SITE_ENABLE_CONF} || ln -s ${SITE_AVL_CONF} ${SITE_ENABLE_CONF}

  # Configure user auth.
  htpasswd -b -c /etc/nginx/.htpasswd ${NB_USER} ${NB_USER_PASS}
  useradd -m ${NB_USER} -G sudo -s /bin/bash && echo "${NB_USER}:${NB_USER_PASS}" | chpasswd
}

generateconfig


# Config & Run RStudio
echo "www-port=$PORT0" >> /etc/rstudio/rserver.conf
echo "server-app-armor-enabled=0" >> /etc/rstudio/rserver.conf 
/usr/lib/rstudio-server/bin/rserver &

#Config & Run Jupyter
mkdir -p $NOTEBOOK_HOME
cd $NOTEBOOK_HOME
export JPASS=`python -c "from notebook.auth import passwd; print passwd('$NB_USER_PASS')"`
export JPASSCONF="c.NotebookApp.password = u'$JPASS'"
jupyter notebook --allow-root --generate-config
echo "$JPASSCONF" >> ~/.jupyter/jupyter_notebook_config.py
jupyter notebook --no-browser --port=$PORT1 --ip=0.0.0.0 --allow-root &

# Run nginx and zeppelin
nginx -g "daemon off;" &
${ZEPPELIN_HOME}/bin/zeppelin.sh
